name: Build OCM Root Component
on:
  push:
    branches:
      - main
    paths:
      - '**_VERSION'
      - 'root-component.yaml'
  workflow_dispatch:
    
jobs:
  ocm:
    runs-on: [ self-hosted, solinas ]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: setup OCM
        uses: open-component-model/ocm-setup-action@main
      - name: Get Podinfo Version
        run: |
          ROOT_COMP_VERSION=`cat ./ROOT_COMP_VERSION`
          PODINFO_CHART_VERSION=`cat ./PODINFO_CHART_VERSION`
          PODINFO_IMAGE_VERSION=`cat ./PODINFO_IMAGE_VERSION`
          echo "ROOT_COMP_VERSION=$ROOT_COMP_VERSION" >> $GITHUB_ENV
          echo "PODINFO_CHART_VERSION=$PODINFO_CHART_VERSION" >> $GITHUB_ENV
          echo "PODINFO_IMAGE_VERSION=$PODINFO_IMAGE_VERSION" >> $GITHUB_ENV
      - name: create OCM CTF Archive
        uses: open-component-model/ocm-action@main
        with:
          action: add_component
          components: root-component.yaml
          directory: .ocm
          version: 0.0.1
          templater: subst
          var_values: |
            ROOT_COMP_VERSION: ${{ env.ROOT_COMP_VERSION}}
            PODINFO_CHART_VERSION: ${{ env.PODINFO_CHART_VERSION}}
            PODINFO_IMAGE_VERSION: ${{ env.PODINFO_IMAGE_VERSION}}
      - name: transfer to OCI Repo
        uses: open-component-model/ocm-action@main
        with:
          action: push_ctf
          comprepo_url: ocmtest.common.repositories.cloud.sap/d032990
          force_push: true
          comprepo_user: ${{ secrets.OCM_JFROG_USER }}
          comprepo_password: ${{ secrets.OCM_JFROG_KEY }}