name: Build OCM Dependend Component
on:
  push:
    branches:
      - main
    paths:
      - 'dep-component.yaml'
jobs:
  ocm:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: setup OCM
        uses: open-component-model/ocm-setup-action@main
      - name: create OCM CTF Archive
        uses: open-component-model/ocm-action@main
        with:
          action: add_component
          components: dep-component.yaml
          directory: .ocm
          version: 0.0.1
      - name: transfer to OCI Repo
        uses: open-component-model/ocm-action@main
        with:
          action: push_ctf
          comprepo_url: ocmtest.common.repositories.cloud.sap/d032990
          force_push: true
          comprepo_user: ${{ secrets.OCM_JFROG_USER }}
          comprepo_password: ${{ secrets.OCM_JFROG_KEY }}